// expense actions
export const ADD_EXPENSE_START = 'ADD_EXPENSE_START'
export const ADD_EXPENSE_SUCCESS = 'ADD_EXPENSE_SUCCESS'
export const ADD_EXPENSE_FAILURE = 'ADD_EXPENSE_FAILURE'
export const EDIT_EXPENSE_START = 'EDIT_EXPENSE_START'
export const EDIT_EXPENSE_SUCCESS = 'EDIT_EXPENSE_SUCCESS'
export const EDIT_EXPENSE_FAILURE = 'EDIT_EXPENSE_FAILURE'
export const REMOVE_EXPENSE_START = 'REMOVE_EXPENSE_START'
export const REMOVE_EXPENSE_SUCCESS = 'REMOVE_EXPENSE_SUCCESS'
export const REMOVE_EXPENSE_FAILURE = 'REMOVE_EXPENSE_FAILURE'

// filter actions
export const SET_TEXT_FILTER = 'SET_TEXT_FILTER'
export const SORT_BY_DATE = 'SORT_BY_DATE'
export const SORT_BY_AMOUNT = 'SORT_BY_AMOUNT'
export const SET_START_DATE = 'SET_START_DATE'
export const SET_END_DATE = 'SET_END_DATE'
